AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'db/schema.rb'

Documentation:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

Style/Encoding:
  Enabled: false

Rails:
  Enabled: true
